### ISSUE TITLE
diagram-tools's notugly.xsl do not cover cluster

### ISSUE THREAD

**Issue by Ron89** [vidarh/diagram-tools#5]
Hi, thanks for the style file. But I can't get it work with my diagram. I am not familiar with xsl file format and the procedure. But I think because my diagram uses cluster, and cluster or sub-graph are not covered in your style file and xsltproc paused with the lack of input?

**Comment by vidarh** [comment]
Hi, thanks for reporting this. Do you have a minimal example, to give me an idea of what you're trying to achieve, and the command line you're using? If xsltproc pauses, that makes me suspect something else is at play too - try passing "--nonet" as an option and see if it still pauses (--nonet prevents xsltproc from trying to make network connections to look up DTDs etc). Also which version of graphviz did you use to generate the diagram?

**Comment by Ron89** [comment]
I am using graphicviz 2.40.1 (it's Arch variant Manjaro, so the packages are usually freakishly new...)

I tried using no net, turned out

    "I/O error : Attempt to load network entity http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd
    diagram.svg:3: warning: failed to load external entity "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"
    "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">"

A sample of the diagram I am drawing:

    digraph Kitty1Util {
        rankdir = LR;
    
        subgraph cluster_Cat0 {
            label = " meowing\nkitten";
            style = filled;
            node [style = filled, color = white, shape = box, width = 2.0 ];
            Kitty1Cat0 [label = " meowing\nkitten"];
            Kitty2Cat0 [label = " meowing\nkitten"];
    
            
            
        }
        
        subgraph cluster_Cat1Memory {
            label = " meowing\nkitten";
            style = filled;
            node [style = filled, color = white, shape = box, width = 2.0 ];
            Kitty1Cat1 [label = " meowing\nkitten" ];
            Kitty2Cat1 [label = " meowing\nkitten"];
            // nodeCat1 [label = " meowing\nkitten"];
        }
    
        subgraph cluster_Cat2 {
            label = " meowing\nkitten";
            style = filled;
            node [style = filled, color = white, shape = box, width = 2.0 ];
            Kitty1Cat2 [label = " meowing\nkitten" ];
            Kitty2Cat2 [label = " meowing\nkitten"];
            Kitty3Cat2 [label = " meowing\nkitten"];
    
        }
    
        subgraph Cat0Cat1 {
            rank = same;
            node [shape = octagon ];
    
            Cat0ReadKitty1 [label = " meowing\nkitten"];
            Cat0ReadKitty2 [label = " meowing\nkitten"];
            Cat0WriteKitty1 [label = " meowing\nkitten"];
            Cat0WriteKitty2 [label = " meowing\nkitten"];
        }
        subgraph Cat1Cat2 {
            node [shape = octagon ];
    
            Cat12Cat2Kitty1 [label = " meowing\nkitten"];
            Cat12Cat2Kitty2 [label = " meowing\nkitten"];
        }
        
        // operations
        Kitty1ToKitty3 [label = " meowing\nkitten", shape = octagon ];
        Kitty3ToKitty1 [label = " meowing\nkitten", shape = octagon ];
        Kitty2ToKitty1 [label = " meowing\nkitten", shape = octagon];
        Kitty3ToKitty2 [label = " meowing\nkitten" , shape = octagon ];
    
        Kitty1Cat2 -> Kitty1ToKitty3 -> Kitty3Cat2;
        Kitty3Cat2 -> Kitty3ToKitty1 -> Kitty1Cat2;
        Kitty3Cat2 -> Kitty3ToKitty2 -> Kitty2Cat2;
        Kitty2Cat2 -> Kitty2ToKitty1 -> Kitty1Cat2;
    
        Kitty1Cat0 -> Cat0ReadKitty1 -> Kitty1Cat1;
        Kitty2Cat0 -> Cat0ReadKitty2 -> Kitty2Cat1;
        Kitty1Cat1 -> Cat0WriteKitty1 -> Kitty1Cat0 [constraint=false];
        Kitty2Cat1 -> Cat0WriteKitty2 -> Kitty2Cat0 [constraint=false];
        Kitty2Cat0 -> Cat0WriteKitty2 -> Kitty2Cat1 [style=invis];
        Kitty1Cat0 -> Cat0WriteKitty1 -> Kitty1Cat1 [style=invis];
        Kitty1Cat1 -> Cat12Cat2Kitty1 -> Kitty1Cat2;
        Kitty2Cat1 -> Cat12Cat2Kitty2 -> Kitty2Cat2;
    }
