### ISSUE TITLE
hrefs on nodes make the node disappear

### ISSUE THREAD

**Issue by rhelms** [vidarh/diagram-tools#6]
href elements in the DOT resulting in a nested g node to contain the link tends to make the whole node disappear.

In the attached files, I've added a simple # reference to the g node, and you will see the preprocessed .svg is fine, but the xsltproc file has the node as disappeared.

I realize this is an old project, so may not be supported any more, but just in case someone can work out how to fix it before I go deep diving into XSLT, I thought I'd start with a report here, first.

[test.dot.txt](https://github.com/vidarh/diagram-tools/files/915583/test.dot.txt)
[test.svg.txt](https://github.com/vidarh/diagram-tools/files/915584/test.svg.txt)
[test-notugly.svg.txt](https://github.com/vidarh/diagram-tools/files/915585/test-notugly.svg.txt)

**Comment by rhelms** [comment]
I solved the issue, but found another that I will use one PR to resolve (if I can fix the other).

The issue that the XSL only processes a limited number of nodes as a part of the `group` template. 

For a non-linked node, the `<g class="node">` will contain `<title>`, `<polygon>` and `<text>` as well as other items.

However, for a linked node, the enclosed `<a>` will be wrapped with a classless `<g>`, which is not picked up in the `group` template.

Adding `<xsl:apply-templates select="svg:g" />` to the end of the `group` template will resolve this, as template matching `svg:g` already caters for links.

I'll try to add an example to the original image, and tests accordingly.

The additional issue is that any custom images appear to not make it in the final transformation.

**Comment by vidarh** [comment]
Cleaning up open pull requests and issues... Thanks for this, and sorry for the very late merge.
